package com.magistuarmory.client.render.model;

import com.magistuarmory.api.client.render.model.ModModelsProvider;
import com.magistuarmory.client.render.model.armor.ArmetModel;
import com.magistuarmory.client.render.model.armor.BarbuteModel;
import com.magistuarmory.client.render.model.armor.BascinetModel;
import com.magistuarmory.client.render.model.armor.ConicHelmetModel;
import com.magistuarmory.client.render.model.armor.CrownArmorModel;
import com.magistuarmory.client.render.model.armor.CrusaderModel;
import com.magistuarmory.client.render.model.armor.DefaultArmorModel;
import com.magistuarmory.client.render.model.armor.DefaultLeggingsModel;
import com.magistuarmory.client.render.model.armor.GrandBascinetModel;
import com.magistuarmory.client.render.model.armor.KettlehatModel;
import com.magistuarmory.client.render.model.armor.MaximilianHelmetModel;
import com.magistuarmory.client.render.model.armor.SalletModel;
import com.magistuarmory.client.render.model.armor.StechhelmModel;
import com.magistuarmory.client.render.model.armor.WingedHussarChestplateModel;
import com.magistuarmory.client.render.model.block.PaviseBlockModel;
import com.magistuarmory.client.render.model.decoration.BigPlumeModel;
import com.magistuarmory.client.render.model.decoration.CaparisonModel;
import com.magistuarmory.client.render.model.decoration.CatEarsModel;
import com.magistuarmory.client.render.model.decoration.CrownModel;
import com.magistuarmory.client.render.model.decoration.EcrancheModel;
import com.magistuarmory.client.render.model.decoration.FlowercrownModel;
import com.magistuarmory.client.render.model.decoration.HoodModel;
import com.magistuarmory.client.render.model.decoration.HornsModel;
import com.magistuarmory.client.render.model.decoration.MiniCrownModel;
import com.magistuarmory.client.render.model.decoration.PlumeLeftModel;
import com.magistuarmory.client.render.model.decoration.PlumeMiddleModel;
import com.magistuarmory.client.render.model.decoration.PlumeRightModel;
import com.magistuarmory.client.render.model.decoration.RondelModel;
import com.magistuarmory.client.render.model.decoration.SurcoatModel;
import com.magistuarmory.client.render.model.decoration.TopDecoration2Model;
import com.magistuarmory.client.render.model.decoration.TopDecorationModel;
import com.magistuarmory.client.render.model.decoration.TorseAndMantleModel;
import com.magistuarmory.client.render.model.decoration.TorseModel;
import com.magistuarmory.client.render.model.item.BucklerModel;
import com.magistuarmory.client.render.model.item.CorruptedRoundShieldModel;
import com.magistuarmory.client.render.model.item.EllipticalShieldModel;
import com.magistuarmory.client.render.model.item.HeaterShieldModel;
import com.magistuarmory.client.render.model.item.KiteShieldModel;
import com.magistuarmory.client.render.model.item.PaviseModel;
import com.magistuarmory.client.render.model.item.RondacheModel;
import com.magistuarmory.client.render.model.item.RoundShieldModel;
import com.magistuarmory.client.render.model.item.TargeModel;
import com.magistuarmory.client.render.model.item.TartscheModel;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.class_5601;
import net.minecraft.class_5607;

@Environment(EnvType.CLIENT)
public class ModModels extends ModModelsProvider {
   public static final ModModels INSTANCE = new ModModels("magistuarmory");
   public static final class_5607 BULLHORNS = HornsModel.createLayer();
   public static final class_5607 TORSE_AND_MANTLE = TorseAndMantleModel.createLayer();
   public static final class_5607 CROWN = CrownModel.createLayer();
   public static final class_5607 FLOWERCROWN = FlowercrownModel.createLayer();
   public static final class_5607 ECRANCHE = EcrancheModel.createLayer();
   public static final class_5607 RONDEL = RondelModel.createLayer();
   public static final class_5607 HOOD = HoodModel.createLayer();
   public static final class_5607 MINICROWN = MiniCrownModel.createLayer();
   public static final class_5607 TORSE = TorseModel.createLayer();
   public static final class_5607 BIG_PLUME = BigPlumeModel.createLayer();
   public static final class_5607 PLUME_LEFT = PlumeLeftModel.createLayer();
   public static final class_5607 PLUME_MIDDLE = PlumeMiddleModel.createLayer();
   public static final class_5607 PLUME_RIGHT = PlumeRightModel.createLayer();
   public static final class_5607 TOP_DECORATION = TopDecorationModel.createLayer();
   public static final class_5607 TOP_DECORATION_2 = TopDecoration2Model.createLayer();
   public static final class_5607 SURCOAT = SurcoatModel.createLayer();
   public static final class_5607 CAPARISON = CaparisonModel.createLayer();
   public static final class_5607 CAT_EARS = CatEarsModel.createLayer();
   public static final class_5601 TORSE_AND_MANTLE_LOCATION = INSTANCE.addDecorationModel("torse_and_mantle", () -> TORSE_AND_MANTLE);
   public static final class_5601 CROWN_LOCATION = INSTANCE.addDecorationModel("crown", () -> CROWN);
   public static final class_5601 FLOWERCROWN_LOCATION = INSTANCE.addDecorationModel("flowercrown", () -> FLOWERCROWN);
   public static final class_5601 MINICROWN_LOCATION = INSTANCE.addDecorationModel("minicrown", () -> MINICROWN);
   public static final class_5601 TORSE_LOCATION = INSTANCE.addDecorationModel("torse", () -> TORSE);
   public static final class_5601 BIG_PLUME_LOCATION = INSTANCE.addDecorationModel("big_plume", () -> BIG_PLUME);
   public static final class_5601 PLUME_LEFT_LOCATION = INSTANCE.addDecorationModel("plume_left", () -> PLUME_LEFT);
   public static final class_5601 PLUME_MIDDLE_LOCATION = INSTANCE.addDecorationModel("plume_middle", () -> PLUME_MIDDLE);
   public static final class_5601 PLUME_RIGHT_LOCATION = INSTANCE.addDecorationModel("plume_right", () -> PLUME_RIGHT);
   public static final class_5601 HOOD_LOCATION = INSTANCE.addDecorationModel("hood", () -> HOOD);
   public static final class_5601 ECRANCHE_LOCATION = INSTANCE.addDecorationModel("ecranche", () -> ECRANCHE);
   public static final class_5601 RONDEL_LOCATION = INSTANCE.addDecorationModel("rondel", () -> RONDEL);
   public static final class_5601 DEMON_HORNS_LOCATION = INSTANCE.addDecorationModel("demon_horns", () -> TOP_DECORATION_2);
   public static final class_5601 FEATHERS_LOCATION = INSTANCE.addDecorationModel("feathers", () -> TOP_DECORATION_2);
   public static final class_5601 GRIFFIN_LOCATION = INSTANCE.addDecorationModel("griffin", () -> TOP_DECORATION_2);
   public static final class_5601 BULLHORNS_LOCATION = INSTANCE.addDecorationModel("bullhorns", () -> TOP_DECORATION);
   public static final class_5601 UNICORN_LOCATION = INSTANCE.addDecorationModel("unicorn", () -> TOP_DECORATION);
   public static final class_5601 DRAGON_LOCATION = INSTANCE.addDecorationModel("dragon", () -> TOP_DECORATION);
   public static final class_5601 TWO_PLUMES_LOCATION = INSTANCE.addDecorationModel("two_plumes", () -> TOP_DECORATION);
   public static final class_5601 ANTLERS_LOCATION = INSTANCE.addDecorationModel("antlers", () -> TOP_DECORATION);
   public static final class_5601 BEAR_LOCATION = INSTANCE.addDecorationModel("bear", () -> TOP_DECORATION);
   public static final class_5601 LILY_LOCATION = INSTANCE.addDecorationModel("lily", () -> TOP_DECORATION);
   public static final class_5601 LION_LOCATION = INSTANCE.addDecorationModel("lion", () -> TOP_DECORATION);
   public static final class_5601 VIKING_HORNS_LOCATION = INSTANCE.addDecorationModel("viking_horns", () -> TOP_DECORATION);
   public static final class_5601 GAZELLE_HORNS_LOCATION = INSTANCE.addDecorationModel("gazelle_horns", () -> TOP_DECORATION);
   public static final class_5601 DUCK_LOCATION = INSTANCE.addDecorationModel("duck", () -> TOP_DECORATION);
   public static final class_5601 SPIKE_LOCATION = INSTANCE.addDecorationModel("spike", () -> TOP_DECORATION);
   public static final class_5601 HORSE_LOCATION = INSTANCE.addDecorationModel("horse", () -> TOP_DECORATION);
   public static final class_5601 SURCOAT_LOCATION = INSTANCE.addDecorationModel("surcoat", () -> SURCOAT);
   public static final class_5601 CAPARISON_LOCATION = INSTANCE.addDecorationModel("caparison", () -> CAPARISON);
   public static final class_5601 CAT_EARS_LOCATION = INSTANCE.addDecorationModel("cat_ears", () -> CAT_EARS);
   public static final class_5601 DEFAULT_ARMOR_LOCATION = INSTANCE.addArmorModel("default", DefaultArmorModel::createLayer);
   public static final class_5601 DEFAULT_LEGGINGS_LOCATION = INSTANCE.addArmorModel("default_leggings", DefaultLeggingsModel::createLayer);
   public static final class_5601 CONIC_HELMET_LOCATION = INSTANCE.addArmorModel("conic_helmet", ConicHelmetModel::createLayer);
   public static final class_5601 CROWN_ARMOR_LOCATION = INSTANCE.addArmorModel("crown", CrownArmorModel::createLayer);
   public static final class_5601 FLOWERCROWN_ARMOR_LOCATION = INSTANCE.addArmorModel("flowercrown", () -> FLOWERCROWN);
   public static final class_5601 MINICROWN_ARMOR_LOCATION = INSTANCE.addArmorModel("minicrown", () -> MINICROWN);
   public static final class_5601 ARMET_LOCATION = INSTANCE.addArmorModel("armet", ArmetModel::createLayer);
   public static final class_5601 STECHHELM_LOCATION = INSTANCE.addArmorModel("stechhelm", StechhelmModel::createLayer);
   public static final class_5601 SALLET_LOCATION = INSTANCE.addArmorModel("sallet", SalletModel::createLayer);
   public static final class_5601 MAXIMILIAN_HELMET_LOCATION = INSTANCE.addArmorModel("maximilian_helmet", MaximilianHelmetModel::createLayer);
   public static final class_5601 KETTLEHAT_LOCATION = INSTANCE.addArmorModel("kettlehat", KettlehatModel::createLayer);
   public static final class_5601 BARBUTE_LOCATION = INSTANCE.addArmorModel("barbute", BarbuteModel::createLayer);
   public static final class_5601 BASCINET_LOCATION = INSTANCE.addArmorModel("bascinet", BascinetModel::createLayer);
   public static final class_5601 GRAND_BASCINET_LOCATION = INSTANCE.addArmorModel("grand_bascinet", GrandBascinetModel::createLayer);
   public static final class_5601 WINGED_HUSSAR_CHESTPLATE_LOCATION = INSTANCE.addArmorModel("wingedhussarchestplate", WingedHussarChestplateModel::createLayer);
   public static final class_5601 CRUSADER_LOCATION = INSTANCE.addArmorModel("crusader", CrusaderModel::createLayer);
   public static final class_5601 HEATER_SHIELD = INSTANCE.addModel("heatershield", HeaterShieldModel::createLayer);
   public static final class_5601 PAVISE = INSTANCE.addModel("pavese", PaviseModel::createLayer);
   public static final class_5601 ROUND_SHIELD = INSTANCE.addModel("roundshield", RoundShieldModel::createLayer);
   public static final class_5601 ELLIPTICAL_SHIELD = INSTANCE.addModel("ellipticalshield", EllipticalShieldModel::createLayer);
   public static final class_5601 TARTSCHE = INSTANCE.addModel("tartsche", TartscheModel::createLayer);
   public static final class_5601 RONDACHE = INSTANCE.addModel("rondache", RondacheModel::createLayer);
   public static final class_5601 KITE_SHIELD = INSTANCE.addModel("kiteshield", KiteShieldModel::createLayer);
   public static final class_5601 BUCKLER = INSTANCE.addModel("buckler", BucklerModel::createLayer);
   public static final class_5601 TARGET = INSTANCE.addModel("target", TargeModel::createLayer);
   public static final class_5601 CORRUPTED_ROUND_SHIELD = INSTANCE.addModel("corruptedroundshield", CorruptedRoundShieldModel::createLayer);
   public static final class_5601 PAVISE_BLOCK_LOCATION = INSTANCE.addModel("pavise_block", PaviseBlockModel::createLayer);

   public ModModels(String modId) {
      super(modId);
   }
}
