package net.kikoz.mcwfurnitures;

import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.fabricmc.fabric.api.object.builder.v1.block.entity.FabricBlockEntityTypeBuilder;
import net.fabricmc.fabric.api.object.builder.v1.entity.FabricEntityTypeBuilder;
import net.kikoz.mcwfurnitures.init.BlockInit;
import net.kikoz.mcwfurnitures.init.ItemInit;
import net.kikoz.mcwfurnitures.init.ScreenHandlerInit;
import net.kikoz.mcwfurnitures.init.SoundsInit;
import net.kikoz.mcwfurnitures.sittable.ChairEntity;
import net.kikoz.mcwfurnitures.sittable.CouchEntity;
import net.kikoz.mcwfurnitures.storage.FurniturekEntity;
import net.minecraft.class_1299;
import net.minecraft.class_1311;
import net.minecraft.class_1761;
import net.minecraft.class_1799;
import net.minecraft.class_2248;
import net.minecraft.class_2378;
import net.minecraft.class_2561;
import net.minecraft.class_259;
import net.minecraft.class_2591;
import net.minecraft.class_265;
import net.minecraft.class_2960;
import net.minecraft.class_4048;
import net.minecraft.class_5321;
import net.minecraft.class_7923;
import net.minecraft.class_7924;

public class MacawsFurniture implements ModInitializer {
   public static final String MOD_ID = "mcwfurnitures";
   public static final class_2960 FURNITURE = class_2960.method_60655("mcwfurnitures", "box_block");
   public static final class_5321<class_1761> FURNITUREGROUP = class_5321.method_29179(
      class_7924.field_44688, class_2960.method_60655("mcwfurnitures", "furnitures")
   );
   public static class_2591<FurniturekEntity> FURNITURE_BLOCK_ENTITY = (class_2591<FurniturekEntity>)class_2378.method_10230(
      class_7923.field_41181,
      FURNITURE,
      FabricBlockEntityTypeBuilder.create(
            FurniturekEntity::new,
            new class_2248[]{
               BlockInit.OAK_WARDROBE,
               BlockInit.OAK_MODERN_WARDROBE,
               BlockInit.OAK_DOUBLE_WARDROBE,
               BlockInit.OAK_BOOKSHELF,
               BlockInit.OAK_BOOKSHELF_CUPBOARD,
               BlockInit.OAK_DRAWER,
               BlockInit.OAK_DOUBLE_DRAWER,
               BlockInit.OAK_BOOKSHELF_DRAWER,
               BlockInit.OAK_LOWER_BOOKSHELF_DRAWER,
               BlockInit.OAK_LARGE_DRAWER,
               BlockInit.OAK_LOWER_TRIPLE_DRAWER,
               BlockInit.OAK_TRIPLE_DRAWER,
               BlockInit.OAK_DRAWER_COUNTER,
               BlockInit.OAK_DOUBLE_DRAWER_COUNTER,
               BlockInit.OAK_CUPBOARD_COUNTER,
               BlockInit.STRIPPED_OAK_WARDROBE,
               BlockInit.STRIPPED_OAK_MODERN_WARDROBE,
               BlockInit.STRIPPED_OAK_DOUBLE_WARDROBE,
               BlockInit.STRIPPED_OAK_BOOKSHELF,
               BlockInit.STRIPPED_OAK_BOOKSHELF_CUPBOARD,
               BlockInit.STRIPPED_OAK_DRAWER,
               BlockInit.STRIPPED_OAK_DOUBLE_DRAWER,
               BlockInit.STRIPPED_OAK_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_OAK_LOWER_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_OAK_LARGE_DRAWER,
               BlockInit.STRIPPED_OAK_LOWER_TRIPLE_DRAWER,
               BlockInit.STRIPPED_OAK_TRIPLE_DRAWER,
               BlockInit.STRIPPED_OAK_DRAWER_COUNTER,
               BlockInit.STRIPPED_OAK_DOUBLE_DRAWER_COUNTER,
               BlockInit.STRIPPED_OAK_CUPBOARD_COUNTER,
               BlockInit.SPRUCE_WARDROBE,
               BlockInit.SPRUCE_MODERN_WARDROBE,
               BlockInit.SPRUCE_DOUBLE_WARDROBE,
               BlockInit.SPRUCE_BOOKSHELF,
               BlockInit.SPRUCE_BOOKSHELF_CUPBOARD,
               BlockInit.SPRUCE_DRAWER,
               BlockInit.SPRUCE_DOUBLE_DRAWER,
               BlockInit.SPRUCE_BOOKSHELF_DRAWER,
               BlockInit.SPRUCE_LOWER_BOOKSHELF_DRAWER,
               BlockInit.SPRUCE_LARGE_DRAWER,
               BlockInit.SPRUCE_LOWER_TRIPLE_DRAWER,
               BlockInit.SPRUCE_TRIPLE_DRAWER,
               BlockInit.SPRUCE_DRAWER_COUNTER,
               BlockInit.SPRUCE_DOUBLE_DRAWER_COUNTER,
               BlockInit.SPRUCE_CUPBOARD_COUNTER,
               BlockInit.STRIPPED_SPRUCE_WARDROBE,
               BlockInit.STRIPPED_SPRUCE_MODERN_WARDROBE,
               BlockInit.STRIPPED_SPRUCE_DOUBLE_WARDROBE,
               BlockInit.STRIPPED_SPRUCE_BOOKSHELF,
               BlockInit.STRIPPED_SPRUCE_BOOKSHELF_CUPBOARD,
               BlockInit.STRIPPED_SPRUCE_DRAWER,
               BlockInit.STRIPPED_SPRUCE_DOUBLE_DRAWER,
               BlockInit.STRIPPED_SPRUCE_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_SPRUCE_LOWER_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_SPRUCE_LARGE_DRAWER,
               BlockInit.STRIPPED_SPRUCE_LOWER_TRIPLE_DRAWER,
               BlockInit.STRIPPED_SPRUCE_TRIPLE_DRAWER,
               BlockInit.STRIPPED_SPRUCE_DRAWER_COUNTER,
               BlockInit.STRIPPED_SPRUCE_DOUBLE_DRAWER_COUNTER,
               BlockInit.STRIPPED_SPRUCE_CUPBOARD_COUNTER,
               BlockInit.BIRCH_WARDROBE,
               BlockInit.BIRCH_MODERN_WARDROBE,
               BlockInit.BIRCH_DOUBLE_WARDROBE,
               BlockInit.BIRCH_BOOKSHELF,
               BlockInit.BIRCH_BOOKSHELF_CUPBOARD,
               BlockInit.BIRCH_DRAWER,
               BlockInit.BIRCH_DOUBLE_DRAWER,
               BlockInit.BIRCH_BOOKSHELF_DRAWER,
               BlockInit.BIRCH_LOWER_BOOKSHELF_DRAWER,
               BlockInit.BIRCH_LARGE_DRAWER,
               BlockInit.BIRCH_LOWER_TRIPLE_DRAWER,
               BlockInit.BIRCH_TRIPLE_DRAWER,
               BlockInit.BIRCH_DRAWER_COUNTER,
               BlockInit.BIRCH_DOUBLE_DRAWER_COUNTER,
               BlockInit.BIRCH_CUPBOARD_COUNTER,
               BlockInit.STRIPPED_BIRCH_WARDROBE,
               BlockInit.STRIPPED_BIRCH_MODERN_WARDROBE,
               BlockInit.STRIPPED_BIRCH_DOUBLE_WARDROBE,
               BlockInit.STRIPPED_BIRCH_BOOKSHELF,
               BlockInit.STRIPPED_BIRCH_BOOKSHELF_CUPBOARD,
               BlockInit.STRIPPED_BIRCH_DRAWER,
               BlockInit.STRIPPED_BIRCH_DOUBLE_DRAWER,
               BlockInit.STRIPPED_BIRCH_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_BIRCH_LOWER_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_BIRCH_LARGE_DRAWER,
               BlockInit.STRIPPED_BIRCH_LOWER_TRIPLE_DRAWER,
               BlockInit.STRIPPED_BIRCH_TRIPLE_DRAWER,
               BlockInit.STRIPPED_BIRCH_DRAWER_COUNTER,
               BlockInit.STRIPPED_BIRCH_DOUBLE_DRAWER_COUNTER,
               BlockInit.STRIPPED_BIRCH_CUPBOARD_COUNTER,
               BlockInit.JUNGLE_WARDROBE,
               BlockInit.JUNGLE_MODERN_WARDROBE,
               BlockInit.JUNGLE_DOUBLE_WARDROBE,
               BlockInit.JUNGLE_BOOKSHELF,
               BlockInit.JUNGLE_BOOKSHELF_CUPBOARD,
               BlockInit.JUNGLE_DRAWER,
               BlockInit.JUNGLE_DOUBLE_DRAWER,
               BlockInit.JUNGLE_BOOKSHELF_DRAWER,
               BlockInit.JUNGLE_LOWER_BOOKSHELF_DRAWER,
               BlockInit.JUNGLE_LARGE_DRAWER,
               BlockInit.JUNGLE_LOWER_TRIPLE_DRAWER,
               BlockInit.JUNGLE_TRIPLE_DRAWER,
               BlockInit.JUNGLE_DRAWER_COUNTER,
               BlockInit.JUNGLE_DOUBLE_DRAWER_COUNTER,
               BlockInit.JUNGLE_CUPBOARD_COUNTER,
               BlockInit.STRIPPED_JUNGLE_WARDROBE,
               BlockInit.STRIPPED_JUNGLE_MODERN_WARDROBE,
               BlockInit.STRIPPED_JUNGLE_DOUBLE_WARDROBE,
               BlockInit.STRIPPED_JUNGLE_BOOKSHELF,
               BlockInit.STRIPPED_JUNGLE_BOOKSHELF_CUPBOARD,
               BlockInit.STRIPPED_JUNGLE_DRAWER,
               BlockInit.STRIPPED_JUNGLE_DOUBLE_DRAWER,
               BlockInit.STRIPPED_JUNGLE_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_JUNGLE_LOWER_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_JUNGLE_LARGE_DRAWER,
               BlockInit.STRIPPED_JUNGLE_LOWER_TRIPLE_DRAWER,
               BlockInit.STRIPPED_JUNGLE_TRIPLE_DRAWER,
               BlockInit.STRIPPED_JUNGLE_DRAWER_COUNTER,
               BlockInit.STRIPPED_JUNGLE_DOUBLE_DRAWER_COUNTER,
               BlockInit.STRIPPED_JUNGLE_CUPBOARD_COUNTER,
               BlockInit.ACACIA_WARDROBE,
               BlockInit.ACACIA_MODERN_WARDROBE,
               BlockInit.ACACIA_DOUBLE_WARDROBE,
               BlockInit.ACACIA_BOOKSHELF,
               BlockInit.ACACIA_BOOKSHELF_CUPBOARD,
               BlockInit.ACACIA_DRAWER,
               BlockInit.ACACIA_DOUBLE_DRAWER,
               BlockInit.ACACIA_BOOKSHELF_DRAWER,
               BlockInit.ACACIA_LOWER_BOOKSHELF_DRAWER,
               BlockInit.ACACIA_LARGE_DRAWER,
               BlockInit.ACACIA_LOWER_TRIPLE_DRAWER,
               BlockInit.ACACIA_TRIPLE_DRAWER,
               BlockInit.ACACIA_DRAWER_COUNTER,
               BlockInit.ACACIA_DOUBLE_DRAWER_COUNTER,
               BlockInit.ACACIA_CUPBOARD_COUNTER,
               BlockInit.STRIPPED_ACACIA_WARDROBE,
               BlockInit.STRIPPED_ACACIA_MODERN_WARDROBE,
               BlockInit.STRIPPED_ACACIA_DOUBLE_WARDROBE,
               BlockInit.STRIPPED_ACACIA_BOOKSHELF,
               BlockInit.STRIPPED_ACACIA_BOOKSHELF_CUPBOARD,
               BlockInit.STRIPPED_ACACIA_DRAWER,
               BlockInit.STRIPPED_ACACIA_DOUBLE_DRAWER,
               BlockInit.STRIPPED_ACACIA_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_ACACIA_LOWER_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_ACACIA_LARGE_DRAWER,
               BlockInit.STRIPPED_ACACIA_LOWER_TRIPLE_DRAWER,
               BlockInit.STRIPPED_ACACIA_TRIPLE_DRAWER,
               BlockInit.STRIPPED_ACACIA_DRAWER_COUNTER,
               BlockInit.STRIPPED_ACACIA_DOUBLE_DRAWER_COUNTER,
               BlockInit.STRIPPED_ACACIA_CUPBOARD_COUNTER,
               BlockInit.DARK_OAK_WARDROBE,
               BlockInit.DARK_OAK_MODERN_WARDROBE,
               BlockInit.DARK_OAK_DOUBLE_WARDROBE,
               BlockInit.DARK_OAK_BOOKSHELF,
               BlockInit.DARK_OAK_BOOKSHELF_CUPBOARD,
               BlockInit.DARK_OAK_DRAWER,
               BlockInit.DARK_OAK_DOUBLE_DRAWER,
               BlockInit.DARK_OAK_BOOKSHELF_DRAWER,
               BlockInit.DARK_OAK_LOWER_BOOKSHELF_DRAWER,
               BlockInit.DARK_OAK_LARGE_DRAWER,
               BlockInit.DARK_OAK_LOWER_TRIPLE_DRAWER,
               BlockInit.DARK_OAK_TRIPLE_DRAWER,
               BlockInit.DARK_OAK_DRAWER_COUNTER,
               BlockInit.DARK_OAK_DOUBLE_DRAWER_COUNTER,
               BlockInit.DARK_OAK_CUPBOARD_COUNTER,
               BlockInit.STRIPPED_DARK_OAK_WARDROBE,
               BlockInit.STRIPPED_DARK_OAK_MODERN_WARDROBE,
               BlockInit.STRIPPED_DARK_OAK_DOUBLE_WARDROBE,
               BlockInit.STRIPPED_DARK_OAK_BOOKSHELF,
               BlockInit.STRIPPED_DARK_OAK_BOOKSHELF_CUPBOARD,
               BlockInit.STRIPPED_DARK_OAK_DRAWER,
               BlockInit.STRIPPED_DARK_OAK_DOUBLE_DRAWER,
               BlockInit.STRIPPED_DARK_OAK_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_DARK_OAK_LOWER_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_DARK_OAK_LARGE_DRAWER,
               BlockInit.STRIPPED_DARK_OAK_LOWER_TRIPLE_DRAWER,
               BlockInit.STRIPPED_DARK_OAK_TRIPLE_DRAWER,
               BlockInit.STRIPPED_DARK_OAK_DRAWER_COUNTER,
               BlockInit.STRIPPED_DARK_OAK_DOUBLE_DRAWER_COUNTER,
               BlockInit.STRIPPED_DARK_OAK_CUPBOARD_COUNTER,
               BlockInit.CRIMSON_WARDROBE,
               BlockInit.CRIMSON_MODERN_WARDROBE,
               BlockInit.CRIMSON_DOUBLE_WARDROBE,
               BlockInit.CRIMSON_BOOKSHELF,
               BlockInit.CRIMSON_BOOKSHELF_CUPBOARD,
               BlockInit.CRIMSON_DRAWER,
               BlockInit.CRIMSON_DOUBLE_DRAWER,
               BlockInit.CRIMSON_BOOKSHELF_DRAWER,
               BlockInit.CRIMSON_LOWER_BOOKSHELF_DRAWER,
               BlockInit.CRIMSON_LARGE_DRAWER,
               BlockInit.CRIMSON_LOWER_TRIPLE_DRAWER,
               BlockInit.CRIMSON_TRIPLE_DRAWER,
               BlockInit.CRIMSON_DRAWER_COUNTER,
               BlockInit.CRIMSON_DOUBLE_DRAWER_COUNTER,
               BlockInit.CRIMSON_CUPBOARD_COUNTER,
               BlockInit.STRIPPED_CRIMSON_WARDROBE,
               BlockInit.STRIPPED_CRIMSON_MODERN_WARDROBE,
               BlockInit.STRIPPED_CRIMSON_DOUBLE_WARDROBE,
               BlockInit.STRIPPED_CRIMSON_BOOKSHELF,
               BlockInit.STRIPPED_CRIMSON_BOOKSHELF_CUPBOARD,
               BlockInit.STRIPPED_CRIMSON_DRAWER,
               BlockInit.STRIPPED_CRIMSON_DOUBLE_DRAWER,
               BlockInit.STRIPPED_CRIMSON_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_CRIMSON_LOWER_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_CRIMSON_LARGE_DRAWER,
               BlockInit.STRIPPED_CRIMSON_LOWER_TRIPLE_DRAWER,
               BlockInit.STRIPPED_CRIMSON_TRIPLE_DRAWER,
               BlockInit.STRIPPED_CRIMSON_DRAWER_COUNTER,
               BlockInit.STRIPPED_CRIMSON_DOUBLE_DRAWER_COUNTER,
               BlockInit.STRIPPED_CRIMSON_CUPBOARD_COUNTER,
               BlockInit.WARPED_WARDROBE,
               BlockInit.WARPED_MODERN_WARDROBE,
               BlockInit.WARPED_DOUBLE_WARDROBE,
               BlockInit.WARPED_BOOKSHELF,
               BlockInit.WARPED_BOOKSHELF_CUPBOARD,
               BlockInit.WARPED_DRAWER,
               BlockInit.WARPED_DOUBLE_DRAWER,
               BlockInit.WARPED_BOOKSHELF_DRAWER,
               BlockInit.WARPED_LOWER_BOOKSHELF_DRAWER,
               BlockInit.WARPED_LARGE_DRAWER,
               BlockInit.WARPED_LOWER_TRIPLE_DRAWER,
               BlockInit.WARPED_TRIPLE_DRAWER,
               BlockInit.WARPED_DRAWER_COUNTER,
               BlockInit.WARPED_DOUBLE_DRAWER_COUNTER,
               BlockInit.WARPED_CUPBOARD_COUNTER,
               BlockInit.STRIPPED_WARPED_WARDROBE,
               BlockInit.STRIPPED_WARPED_MODERN_WARDROBE,
               BlockInit.STRIPPED_WARPED_DOUBLE_WARDROBE,
               BlockInit.STRIPPED_WARPED_BOOKSHELF,
               BlockInit.STRIPPED_WARPED_BOOKSHELF_CUPBOARD,
               BlockInit.STRIPPED_WARPED_DRAWER,
               BlockInit.STRIPPED_WARPED_DOUBLE_DRAWER,
               BlockInit.STRIPPED_WARPED_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_WARPED_LOWER_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_WARPED_LARGE_DRAWER,
               BlockInit.STRIPPED_WARPED_LOWER_TRIPLE_DRAWER,
               BlockInit.STRIPPED_WARPED_TRIPLE_DRAWER,
               BlockInit.STRIPPED_WARPED_DRAWER_COUNTER,
               BlockInit.STRIPPED_WARPED_DOUBLE_DRAWER_COUNTER,
               BlockInit.STRIPPED_WARPED_CUPBOARD_COUNTER,
               BlockInit.MANGROVE_WARDROBE,
               BlockInit.MANGROVE_MODERN_WARDROBE,
               BlockInit.MANGROVE_DOUBLE_WARDROBE,
               BlockInit.MANGROVE_BOOKSHELF,
               BlockInit.MANGROVE_BOOKSHELF_CUPBOARD,
               BlockInit.MANGROVE_DRAWER,
               BlockInit.MANGROVE_DOUBLE_DRAWER,
               BlockInit.MANGROVE_BOOKSHELF_DRAWER,
               BlockInit.MANGROVE_LOWER_BOOKSHELF_DRAWER,
               BlockInit.MANGROVE_LARGE_DRAWER,
               BlockInit.MANGROVE_LOWER_TRIPLE_DRAWER,
               BlockInit.MANGROVE_TRIPLE_DRAWER,
               BlockInit.MANGROVE_DRAWER_COUNTER,
               BlockInit.MANGROVE_DOUBLE_DRAWER_COUNTER,
               BlockInit.MANGROVE_CUPBOARD_COUNTER,
               BlockInit.STRIPPED_MANGROVE_WARDROBE,
               BlockInit.STRIPPED_MANGROVE_MODERN_WARDROBE,
               BlockInit.STRIPPED_MANGROVE_DOUBLE_WARDROBE,
               BlockInit.STRIPPED_MANGROVE_BOOKSHELF,
               BlockInit.STRIPPED_MANGROVE_BOOKSHELF_CUPBOARD,
               BlockInit.STRIPPED_MANGROVE_DRAWER,
               BlockInit.STRIPPED_MANGROVE_DOUBLE_DRAWER,
               BlockInit.STRIPPED_MANGROVE_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_MANGROVE_LOWER_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_MANGROVE_LARGE_DRAWER,
               BlockInit.STRIPPED_MANGROVE_LOWER_TRIPLE_DRAWER,
               BlockInit.STRIPPED_MANGROVE_TRIPLE_DRAWER,
               BlockInit.STRIPPED_MANGROVE_DRAWER_COUNTER,
               BlockInit.STRIPPED_MANGROVE_DOUBLE_DRAWER_COUNTER,
               BlockInit.STRIPPED_MANGROVE_CUPBOARD_COUNTER,
               BlockInit.CHERRY_WARDROBE,
               BlockInit.CHERRY_MODERN_WARDROBE,
               BlockInit.CHERRY_DOUBLE_WARDROBE,
               BlockInit.CHERRY_BOOKSHELF,
               BlockInit.CHERRY_BOOKSHELF_CUPBOARD,
               BlockInit.CHERRY_DRAWER,
               BlockInit.CHERRY_DOUBLE_DRAWER,
               BlockInit.CHERRY_BOOKSHELF_DRAWER,
               BlockInit.CHERRY_LOWER_BOOKSHELF_DRAWER,
               BlockInit.CHERRY_LARGE_DRAWER,
               BlockInit.CHERRY_LOWER_TRIPLE_DRAWER,
               BlockInit.CHERRY_TRIPLE_DRAWER,
               BlockInit.CHERRY_DRAWER_COUNTER,
               BlockInit.CHERRY_DOUBLE_DRAWER_COUNTER,
               BlockInit.CHERRY_CUPBOARD_COUNTER,
               BlockInit.STRIPPED_CHERRY_WARDROBE,
               BlockInit.STRIPPED_CHERRY_MODERN_WARDROBE,
               BlockInit.STRIPPED_CHERRY_DOUBLE_WARDROBE,
               BlockInit.STRIPPED_CHERRY_BOOKSHELF,
               BlockInit.STRIPPED_CHERRY_BOOKSHELF_CUPBOARD,
               BlockInit.STRIPPED_CHERRY_DRAWER,
               BlockInit.STRIPPED_CHERRY_DOUBLE_DRAWER,
               BlockInit.STRIPPED_CHERRY_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_CHERRY_LOWER_BOOKSHELF_DRAWER,
               BlockInit.STRIPPED_CHERRY_LARGE_DRAWER,
               BlockInit.STRIPPED_CHERRY_LOWER_TRIPLE_DRAWER,
               BlockInit.STRIPPED_CHERRY_TRIPLE_DRAWER,
               BlockInit.STRIPPED_CHERRY_DRAWER_COUNTER,
               BlockInit.STRIPPED_CHERRY_DOUBLE_DRAWER_COUNTER,
               BlockInit.STRIPPED_CHERRY_CUPBOARD_COUNTER,
               BlockInit.OAK_KITCHEN_CABINET,
               BlockInit.OAK_DOUBLE_KITCHEN_CABINET,
               BlockInit.OAK_GLASS_KITCHEN_CABINET,
               BlockInit.STRIPPED_OAK_KITCHEN_CABINET,
               BlockInit.STRIPPED_OAK_DOUBLE_KITCHEN_CABINET,
               BlockInit.STRIPPED_OAK_GLASS_KITCHEN_CABINET,
               BlockInit.SPRUCE_KITCHEN_CABINET,
               BlockInit.SPRUCE_DOUBLE_KITCHEN_CABINET,
               BlockInit.SPRUCE_GLASS_KITCHEN_CABINET,
               BlockInit.STRIPPED_SPRUCE_KITCHEN_CABINET,
               BlockInit.STRIPPED_SPRUCE_DOUBLE_KITCHEN_CABINET,
               BlockInit.STRIPPED_SPRUCE_GLASS_KITCHEN_CABINET,
               BlockInit.BIRCH_KITCHEN_CABINET,
               BlockInit.BIRCH_DOUBLE_KITCHEN_CABINET,
               BlockInit.BIRCH_GLASS_KITCHEN_CABINET,
               BlockInit.STRIPPED_BIRCH_KITCHEN_CABINET,
               BlockInit.STRIPPED_BIRCH_DOUBLE_KITCHEN_CABINET,
               BlockInit.STRIPPED_BIRCH_GLASS_KITCHEN_CABINET,
               BlockInit.JUNGLE_KITCHEN_CABINET,
               BlockInit.JUNGLE_DOUBLE_KITCHEN_CABINET,
               BlockInit.JUNGLE_GLASS_KITCHEN_CABINET,
               BlockInit.STRIPPED_JUNGLE_KITCHEN_CABINET,
               BlockInit.STRIPPED_JUNGLE_DOUBLE_KITCHEN_CABINET,
               BlockInit.STRIPPED_JUNGLE_GLASS_KITCHEN_CABINET,
               BlockInit.ACACIA_KITCHEN_CABINET,
               BlockInit.ACACIA_DOUBLE_KITCHEN_CABINET,
               BlockInit.ACACIA_GLASS_KITCHEN_CABINET,
               BlockInit.STRIPPED_ACACIA_KITCHEN_CABINET,
               BlockInit.STRIPPED_ACACIA_DOUBLE_KITCHEN_CABINET,
               BlockInit.STRIPPED_ACACIA_GLASS_KITCHEN_CABINET,
               BlockInit.DARK_OAK_KITCHEN_CABINET,
               BlockInit.DARK_OAK_DOUBLE_KITCHEN_CABINET,
               BlockInit.DARK_OAK_GLASS_KITCHEN_CABINET,
               BlockInit.STRIPPED_DARK_OAK_KITCHEN_CABINET,
               BlockInit.STRIPPED_DARK_OAK_DOUBLE_KITCHEN_CABINET,
               BlockInit.STRIPPED_DARK_OAK_GLASS_KITCHEN_CABINET,
               BlockInit.CRIMSON_KITCHEN_CABINET,
               BlockInit.CRIMSON_DOUBLE_KITCHEN_CABINET,
               BlockInit.CRIMSON_GLASS_KITCHEN_CABINET,
               BlockInit.STRIPPED_CRIMSON_KITCHEN_CABINET,
               BlockInit.STRIPPED_CRIMSON_DOUBLE_KITCHEN_CABINET,
               BlockInit.STRIPPED_CRIMSON_GLASS_KITCHEN_CABINET,
               BlockInit.WARPED_KITCHEN_CABINET,
               BlockInit.WARPED_DOUBLE_KITCHEN_CABINET,
               BlockInit.WARPED_GLASS_KITCHEN_CABINET,
               BlockInit.STRIPPED_WARPED_KITCHEN_CABINET,
               BlockInit.STRIPPED_WARPED_DOUBLE_KITCHEN_CABINET,
               BlockInit.STRIPPED_WARPED_GLASS_KITCHEN_CABINET,
               BlockInit.MANGROVE_KITCHEN_CABINET,
               BlockInit.MANGROVE_DOUBLE_KITCHEN_CABINET,
               BlockInit.MANGROVE_GLASS_KITCHEN_CABINET,
               BlockInit.STRIPPED_MANGROVE_KITCHEN_CABINET,
               BlockInit.STRIPPED_MANGROVE_DOUBLE_KITCHEN_CABINET,
               BlockInit.STRIPPED_MANGROVE_GLASS_KITCHEN_CABINET,
               BlockInit.CHERRY_KITCHEN_CABINET,
               BlockInit.CHERRY_DOUBLE_KITCHEN_CABINET,
               BlockInit.CHERRY_GLASS_KITCHEN_CABINET,
               BlockInit.STRIPPED_CHERRY_KITCHEN_CABINET,
               BlockInit.STRIPPED_CHERRY_DOUBLE_KITCHEN_CABINET,
               BlockInit.OAK_COUNTER,
               BlockInit.SPRUCE_COUNTER,
               BlockInit.BIRCH_COUNTER,
               BlockInit.JUNGLE_COUNTER,
               BlockInit.ACACIA_COUNTER,
               BlockInit.DARK_OAK_COUNTER,
               BlockInit.CRIMSON_COUNTER,
               BlockInit.WARPED_COUNTER,
               BlockInit.MANGROVE_COUNTER,
               BlockInit.CHERRY_COUNTER,
               BlockInit.STRIPPED_OAK_COUNTER,
               BlockInit.STRIPPED_SPRUCE_COUNTER,
               BlockInit.STRIPPED_BIRCH_COUNTER,
               BlockInit.STRIPPED_JUNGLE_COUNTER,
               BlockInit.STRIPPED_ACACIA_COUNTER,
               BlockInit.STRIPPED_DARK_OAK_COUNTER,
               BlockInit.STRIPPED_CRIMSON_COUNTER,
               BlockInit.STRIPPED_WARPED_COUNTER,
               BlockInit.STRIPPED_MANGROVE_COUNTER,
               BlockInit.STRIPPED_CHERRY_COUNTER,
               BlockInit.STRIPPED_CHERRY_GLASS_KITCHEN_CABINET
            }
         )
         .build(null)
   );
   public static final class_1299<ChairEntity> CHAIR_ENTITY_TYPE = FabricEntityTypeBuilder.create(class_1311.field_17715, ChairEntity::new)
      .dimensions(class_4048.method_18385(1.001F, 1.001F))
      .build();
   public static final class_1299<CouchEntity> COUCH_ENTITY_TYPE = FabricEntityTypeBuilder.create(class_1311.field_17715, CouchEntity::new)
      .dimensions(class_4048.method_18385(1.001F, 1.001F))
      .build();

   public void onInitialize() {
      BlockInit.registerModBlocks();
      ItemInit.registerModItems();
      ScreenHandlerInit.init();
      SoundsInit soundsInit = new SoundsInit();
      SoundsInit.registerSoundEvents();
      class_2378.method_10230(class_7923.field_41177, class_2960.method_60655("mcwfurnitures", "chair_entity"), CHAIR_ENTITY_TYPE);
      class_2378.method_10230(class_7923.field_41177, class_2960.method_60655("mcwfurnitures", "couch_entity"), COUCH_ENTITY_TYPE);
      class_2378.method_39197(
         class_7923.field_44687,
         FURNITUREGROUP,
         FabricItemGroup.builder()
            .method_47321(class_2561.method_43471("itemGroup.mcwfurnitures"))
            .method_47320(() -> new class_1799(BlockInit.OAK_WARDROBE))
            .method_47317((displayContext, entries) -> {
               entries.method_45421(ItemInit.CABINET_DOOR);
               entries.method_45421(ItemInit.CABINET_DRAWER);
               entries.method_45421(BlockInit.OAK_WARDROBE);
               entries.method_45421(BlockInit.OAK_MODERN_WARDROBE);
               entries.method_45421(BlockInit.OAK_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.OAK_BOOKSHELF);
               entries.method_45421(BlockInit.OAK_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.OAK_DRAWER);
               entries.method_45421(BlockInit.OAK_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.OAK_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.OAK_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.OAK_LARGE_DRAWER);
               entries.method_45421(BlockInit.OAK_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.OAK_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.OAK_DESK);
               entries.method_45421(BlockInit.OAK_COVERED_DESK);
               entries.method_45421(BlockInit.OAK_MODERN_DESK);
               entries.method_45421(BlockInit.OAK_TABLE);
               entries.method_45421(BlockInit.OAK_END_TABLE);
               entries.method_45421(BlockInit.OAK_COFFEE_TABLE);
               entries.method_45421(BlockInit.OAK_GLASS_TABLE);
               entries.method_45421(BlockInit.OAK_CHAIR);
               entries.method_45421(BlockInit.OAK_MODERN_CHAIR);
               entries.method_45421(BlockInit.OAK_STRIPED_CHAIR);
               entries.method_45421(BlockInit.OAK_STOOL_CHAIR);
               entries.method_45421(BlockInit.OAK_COUNTER);
               entries.method_45421(BlockInit.OAK_DRAWER_COUNTER);
               entries.method_45421(BlockInit.OAK_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.OAK_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.BIRCH_WARDROBE);
               entries.method_45421(BlockInit.BIRCH_MODERN_WARDROBE);
               entries.method_45421(BlockInit.BIRCH_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.BIRCH_BOOKSHELF);
               entries.method_45421(BlockInit.BIRCH_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.BIRCH_DRAWER);
               entries.method_45421(BlockInit.BIRCH_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.BIRCH_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.BIRCH_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.BIRCH_LARGE_DRAWER);
               entries.method_45421(BlockInit.BIRCH_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.BIRCH_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.BIRCH_DESK);
               entries.method_45421(BlockInit.BIRCH_COVERED_DESK);
               entries.method_45421(BlockInit.BIRCH_MODERN_DESK);
               entries.method_45421(BlockInit.BIRCH_TABLE);
               entries.method_45421(BlockInit.BIRCH_END_TABLE);
               entries.method_45421(BlockInit.BIRCH_COFFEE_TABLE);
               entries.method_45421(BlockInit.BIRCH_GLASS_TABLE);
               entries.method_45421(BlockInit.BIRCH_CHAIR);
               entries.method_45421(BlockInit.BIRCH_MODERN_CHAIR);
               entries.method_45421(BlockInit.BIRCH_STRIPED_CHAIR);
               entries.method_45421(BlockInit.BIRCH_STOOL_CHAIR);
               entries.method_45421(BlockInit.BIRCH_COUNTER);
               entries.method_45421(BlockInit.BIRCH_DRAWER_COUNTER);
               entries.method_45421(BlockInit.BIRCH_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.BIRCH_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.SPRUCE_WARDROBE);
               entries.method_45421(BlockInit.SPRUCE_MODERN_WARDROBE);
               entries.method_45421(BlockInit.SPRUCE_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.SPRUCE_BOOKSHELF);
               entries.method_45421(BlockInit.SPRUCE_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.SPRUCE_DRAWER);
               entries.method_45421(BlockInit.SPRUCE_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.SPRUCE_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.SPRUCE_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.SPRUCE_LARGE_DRAWER);
               entries.method_45421(BlockInit.SPRUCE_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.SPRUCE_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.SPRUCE_DESK);
               entries.method_45421(BlockInit.SPRUCE_COVERED_DESK);
               entries.method_45421(BlockInit.SPRUCE_MODERN_DESK);
               entries.method_45421(BlockInit.SPRUCE_TABLE);
               entries.method_45421(BlockInit.SPRUCE_END_TABLE);
               entries.method_45421(BlockInit.SPRUCE_COFFEE_TABLE);
               entries.method_45421(BlockInit.SPRUCE_GLASS_TABLE);
               entries.method_45421(BlockInit.SPRUCE_CHAIR);
               entries.method_45421(BlockInit.SPRUCE_MODERN_CHAIR);
               entries.method_45421(BlockInit.SPRUCE_STRIPED_CHAIR);
               entries.method_45421(BlockInit.SPRUCE_STOOL_CHAIR);
               entries.method_45421(BlockInit.SPRUCE_COUNTER);
               entries.method_45421(BlockInit.SPRUCE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.SPRUCE_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.SPRUCE_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.JUNGLE_WARDROBE);
               entries.method_45421(BlockInit.JUNGLE_MODERN_WARDROBE);
               entries.method_45421(BlockInit.JUNGLE_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.JUNGLE_BOOKSHELF);
               entries.method_45421(BlockInit.JUNGLE_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.JUNGLE_DRAWER);
               entries.method_45421(BlockInit.JUNGLE_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.JUNGLE_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.JUNGLE_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.JUNGLE_LARGE_DRAWER);
               entries.method_45421(BlockInit.JUNGLE_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.JUNGLE_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.JUNGLE_DESK);
               entries.method_45421(BlockInit.JUNGLE_COVERED_DESK);
               entries.method_45421(BlockInit.JUNGLE_MODERN_DESK);
               entries.method_45421(BlockInit.JUNGLE_TABLE);
               entries.method_45421(BlockInit.JUNGLE_END_TABLE);
               entries.method_45421(BlockInit.JUNGLE_COFFEE_TABLE);
               entries.method_45421(BlockInit.JUNGLE_GLASS_TABLE);
               entries.method_45421(BlockInit.JUNGLE_CHAIR);
               entries.method_45421(BlockInit.JUNGLE_MODERN_CHAIR);
               entries.method_45421(BlockInit.JUNGLE_STRIPED_CHAIR);
               entries.method_45421(BlockInit.JUNGLE_STOOL_CHAIR);
               entries.method_45421(BlockInit.JUNGLE_COUNTER);
               entries.method_45421(BlockInit.JUNGLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.JUNGLE_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.JUNGLE_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.ACACIA_WARDROBE);
               entries.method_45421(BlockInit.ACACIA_MODERN_WARDROBE);
               entries.method_45421(BlockInit.ACACIA_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.ACACIA_BOOKSHELF);
               entries.method_45421(BlockInit.ACACIA_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.ACACIA_DRAWER);
               entries.method_45421(BlockInit.ACACIA_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.ACACIA_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.ACACIA_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.ACACIA_LARGE_DRAWER);
               entries.method_45421(BlockInit.ACACIA_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.ACACIA_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.ACACIA_DESK);
               entries.method_45421(BlockInit.ACACIA_COVERED_DESK);
               entries.method_45421(BlockInit.ACACIA_MODERN_DESK);
               entries.method_45421(BlockInit.ACACIA_TABLE);
               entries.method_45421(BlockInit.ACACIA_END_TABLE);
               entries.method_45421(BlockInit.ACACIA_COFFEE_TABLE);
               entries.method_45421(BlockInit.ACACIA_GLASS_TABLE);
               entries.method_45421(BlockInit.ACACIA_CHAIR);
               entries.method_45421(BlockInit.ACACIA_MODERN_CHAIR);
               entries.method_45421(BlockInit.ACACIA_STRIPED_CHAIR);
               entries.method_45421(BlockInit.ACACIA_STOOL_CHAIR);
               entries.method_45421(BlockInit.ACACIA_COUNTER);
               entries.method_45421(BlockInit.ACACIA_DRAWER_COUNTER);
               entries.method_45421(BlockInit.ACACIA_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.ACACIA_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.DARK_OAK_WARDROBE);
               entries.method_45421(BlockInit.DARK_OAK_MODERN_WARDROBE);
               entries.method_45421(BlockInit.DARK_OAK_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.DARK_OAK_BOOKSHELF);
               entries.method_45421(BlockInit.DARK_OAK_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.DARK_OAK_DRAWER);
               entries.method_45421(BlockInit.DARK_OAK_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.DARK_OAK_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.DARK_OAK_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.DARK_OAK_LARGE_DRAWER);
               entries.method_45421(BlockInit.DARK_OAK_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.DARK_OAK_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.DARK_OAK_DESK);
               entries.method_45421(BlockInit.DARK_OAK_COVERED_DESK);
               entries.method_45421(BlockInit.DARK_OAK_MODERN_DESK);
               entries.method_45421(BlockInit.DARK_OAK_TABLE);
               entries.method_45421(BlockInit.DARK_OAK_END_TABLE);
               entries.method_45421(BlockInit.DARK_OAK_COFFEE_TABLE);
               entries.method_45421(BlockInit.DARK_OAK_GLASS_TABLE);
               entries.method_45421(BlockInit.DARK_OAK_CHAIR);
               entries.method_45421(BlockInit.DARK_OAK_MODERN_CHAIR);
               entries.method_45421(BlockInit.DARK_OAK_STRIPED_CHAIR);
               entries.method_45421(BlockInit.DARK_OAK_STOOL_CHAIR);
               entries.method_45421(BlockInit.DARK_OAK_COUNTER);
               entries.method_45421(BlockInit.DARK_OAK_DRAWER_COUNTER);
               entries.method_45421(BlockInit.DARK_OAK_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.DARK_OAK_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.CRIMSON_WARDROBE);
               entries.method_45421(BlockInit.CRIMSON_MODERN_WARDROBE);
               entries.method_45421(BlockInit.CRIMSON_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.CRIMSON_BOOKSHELF);
               entries.method_45421(BlockInit.CRIMSON_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.CRIMSON_DRAWER);
               entries.method_45421(BlockInit.CRIMSON_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.CRIMSON_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.CRIMSON_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.CRIMSON_LARGE_DRAWER);
               entries.method_45421(BlockInit.CRIMSON_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.CRIMSON_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.CRIMSON_DESK);
               entries.method_45421(BlockInit.CRIMSON_COVERED_DESK);
               entries.method_45421(BlockInit.CRIMSON_MODERN_DESK);
               entries.method_45421(BlockInit.CRIMSON_TABLE);
               entries.method_45421(BlockInit.CRIMSON_END_TABLE);
               entries.method_45421(BlockInit.CRIMSON_COFFEE_TABLE);
               entries.method_45421(BlockInit.CRIMSON_GLASS_TABLE);
               entries.method_45421(BlockInit.CRIMSON_CHAIR);
               entries.method_45421(BlockInit.CRIMSON_MODERN_CHAIR);
               entries.method_45421(BlockInit.CRIMSON_STRIPED_CHAIR);
               entries.method_45421(BlockInit.CRIMSON_STOOL_CHAIR);
               entries.method_45421(BlockInit.CRIMSON_COUNTER);
               entries.method_45421(BlockInit.CRIMSON_DRAWER_COUNTER);
               entries.method_45421(BlockInit.CRIMSON_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.CRIMSON_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.WARPED_WARDROBE);
               entries.method_45421(BlockInit.WARPED_MODERN_WARDROBE);
               entries.method_45421(BlockInit.WARPED_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.WARPED_BOOKSHELF);
               entries.method_45421(BlockInit.WARPED_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.WARPED_DRAWER);
               entries.method_45421(BlockInit.WARPED_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.WARPED_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.WARPED_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.WARPED_LARGE_DRAWER);
               entries.method_45421(BlockInit.WARPED_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.WARPED_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.WARPED_DESK);
               entries.method_45421(BlockInit.WARPED_COVERED_DESK);
               entries.method_45421(BlockInit.WARPED_MODERN_DESK);
               entries.method_45421(BlockInit.WARPED_TABLE);
               entries.method_45421(BlockInit.WARPED_END_TABLE);
               entries.method_45421(BlockInit.WARPED_COFFEE_TABLE);
               entries.method_45421(BlockInit.WARPED_GLASS_TABLE);
               entries.method_45421(BlockInit.WARPED_CHAIR);
               entries.method_45421(BlockInit.WARPED_MODERN_CHAIR);
               entries.method_45421(BlockInit.WARPED_STRIPED_CHAIR);
               entries.method_45421(BlockInit.WARPED_STOOL_CHAIR);
               entries.method_45421(BlockInit.WARPED_COUNTER);
               entries.method_45421(BlockInit.WARPED_DRAWER_COUNTER);
               entries.method_45421(BlockInit.WARPED_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.WARPED_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.MANGROVE_WARDROBE);
               entries.method_45421(BlockInit.MANGROVE_MODERN_WARDROBE);
               entries.method_45421(BlockInit.MANGROVE_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.MANGROVE_BOOKSHELF);
               entries.method_45421(BlockInit.MANGROVE_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.MANGROVE_DRAWER);
               entries.method_45421(BlockInit.MANGROVE_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.MANGROVE_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.MANGROVE_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.MANGROVE_LARGE_DRAWER);
               entries.method_45421(BlockInit.MANGROVE_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.MANGROVE_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.MANGROVE_DESK);
               entries.method_45421(BlockInit.MANGROVE_COVERED_DESK);
               entries.method_45421(BlockInit.MANGROVE_MODERN_DESK);
               entries.method_45421(BlockInit.MANGROVE_TABLE);
               entries.method_45421(BlockInit.MANGROVE_END_TABLE);
               entries.method_45421(BlockInit.MANGROVE_COFFEE_TABLE);
               entries.method_45421(BlockInit.MANGROVE_GLASS_TABLE);
               entries.method_45421(BlockInit.MANGROVE_CHAIR);
               entries.method_45421(BlockInit.MANGROVE_MODERN_CHAIR);
               entries.method_45421(BlockInit.MANGROVE_STRIPED_CHAIR);
               entries.method_45421(BlockInit.MANGROVE_STOOL_CHAIR);
               entries.method_45421(BlockInit.MANGROVE_COUNTER);
               entries.method_45421(BlockInit.MANGROVE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.MANGROVE_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.MANGROVE_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.CHERRY_WARDROBE);
               entries.method_45421(BlockInit.CHERRY_MODERN_WARDROBE);
               entries.method_45421(BlockInit.CHERRY_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.CHERRY_BOOKSHELF);
               entries.method_45421(BlockInit.CHERRY_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.CHERRY_DRAWER);
               entries.method_45421(BlockInit.CHERRY_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.CHERRY_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.CHERRY_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.CHERRY_LARGE_DRAWER);
               entries.method_45421(BlockInit.CHERRY_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.CHERRY_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.CHERRY_DESK);
               entries.method_45421(BlockInit.CHERRY_COVERED_DESK);
               entries.method_45421(BlockInit.CHERRY_MODERN_DESK);
               entries.method_45421(BlockInit.CHERRY_TABLE);
               entries.method_45421(BlockInit.CHERRY_END_TABLE);
               entries.method_45421(BlockInit.CHERRY_COFFEE_TABLE);
               entries.method_45421(BlockInit.CHERRY_GLASS_TABLE);
               entries.method_45421(BlockInit.CHERRY_CHAIR);
               entries.method_45421(BlockInit.CHERRY_MODERN_CHAIR);
               entries.method_45421(BlockInit.CHERRY_STRIPED_CHAIR);
               entries.method_45421(BlockInit.CHERRY_STOOL_CHAIR);
               entries.method_45421(BlockInit.CHERRY_COUNTER);
               entries.method_45421(BlockInit.CHERRY_DRAWER_COUNTER);
               entries.method_45421(BlockInit.CHERRY_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.CHERRY_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_OAK_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_OAK_MODERN_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_OAK_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_OAK_BOOKSHELF);
               entries.method_45421(BlockInit.STRIPPED_OAK_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.STRIPPED_OAK_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_OAK_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_OAK_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_OAK_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_OAK_LARGE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_OAK_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_OAK_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_OAK_DESK);
               entries.method_45421(BlockInit.STRIPPED_OAK_COVERED_DESK);
               entries.method_45421(BlockInit.STRIPPED_OAK_MODERN_DESK);
               entries.method_45421(BlockInit.STRIPPED_OAK_TABLE);
               entries.method_45421(BlockInit.STRIPPED_OAK_END_TABLE);
               entries.method_45421(BlockInit.STRIPPED_OAK_COFFEE_TABLE);
               entries.method_45421(BlockInit.STRIPPED_OAK_GLASS_TABLE);
               entries.method_45421(BlockInit.STRIPPED_OAK_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_OAK_MODERN_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_OAK_STRIPED_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_OAK_STOOL_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_OAK_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_OAK_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_OAK_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_OAK_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_MODERN_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_BOOKSHELF);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_LARGE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_DESK);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_COVERED_DESK);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_MODERN_DESK);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_TABLE);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_END_TABLE);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_COFFEE_TABLE);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_GLASS_TABLE);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_MODERN_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_STRIPED_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_STOOL_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_MODERN_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_BOOKSHELF);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_LARGE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_DESK);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_COVERED_DESK);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_MODERN_DESK);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_TABLE);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_END_TABLE);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_COFFEE_TABLE);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_GLASS_TABLE);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_MODERN_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_STRIPED_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_STOOL_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_MODERN_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_BOOKSHELF);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_LARGE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_DESK);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_COVERED_DESK);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_MODERN_DESK);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_TABLE);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_END_TABLE);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_COFFEE_TABLE);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_GLASS_TABLE);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_MODERN_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_STRIPED_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_STOOL_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_MODERN_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_BOOKSHELF);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_LARGE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_DESK);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_COVERED_DESK);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_MODERN_DESK);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_TABLE);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_END_TABLE);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_COFFEE_TABLE);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_GLASS_TABLE);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_MODERN_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_STRIPED_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_STOOL_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_MODERN_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_BOOKSHELF);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_LARGE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_DESK);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_COVERED_DESK);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_MODERN_DESK);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_TABLE);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_END_TABLE);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_COFFEE_TABLE);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_GLASS_TABLE);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_MODERN_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_STRIPED_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_STOOL_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_MODERN_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_BOOKSHELF);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_LARGE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_DESK);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_COVERED_DESK);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_MODERN_DESK);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_TABLE);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_END_TABLE);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_COFFEE_TABLE);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_GLASS_TABLE);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_MODERN_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_STRIPED_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_STOOL_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_WARPED_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_WARPED_MODERN_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_WARPED_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_WARPED_BOOKSHELF);
               entries.method_45421(BlockInit.STRIPPED_WARPED_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.STRIPPED_WARPED_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_WARPED_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_WARPED_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_WARPED_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_WARPED_LARGE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_WARPED_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_WARPED_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_WARPED_DESK);
               entries.method_45421(BlockInit.STRIPPED_WARPED_COVERED_DESK);
               entries.method_45421(BlockInit.STRIPPED_WARPED_MODERN_DESK);
               entries.method_45421(BlockInit.STRIPPED_WARPED_TABLE);
               entries.method_45421(BlockInit.STRIPPED_WARPED_END_TABLE);
               entries.method_45421(BlockInit.STRIPPED_WARPED_COFFEE_TABLE);
               entries.method_45421(BlockInit.STRIPPED_WARPED_GLASS_TABLE);
               entries.method_45421(BlockInit.STRIPPED_WARPED_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_WARPED_MODERN_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_WARPED_STRIPED_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_WARPED_STOOL_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_WARPED_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_WARPED_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_WARPED_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_WARPED_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_MODERN_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_BOOKSHELF);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_LARGE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_DESK);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_COVERED_DESK);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_MODERN_DESK);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_TABLE);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_END_TABLE);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_COFFEE_TABLE);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_GLASS_TABLE);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_MODERN_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_STRIPED_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_STOOL_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_MODERN_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_DOUBLE_WARDROBE);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_BOOKSHELF);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_BOOKSHELF_CUPBOARD);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_DOUBLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_LOWER_BOOKSHELF_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_LARGE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_LOWER_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_TRIPLE_DRAWER);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_DESK);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_COVERED_DESK);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_MODERN_DESK);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_TABLE);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_END_TABLE);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_COFFEE_TABLE);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_GLASS_TABLE);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_MODERN_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_STRIPED_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_STOOL_CHAIR);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_DOUBLE_DRAWER_COUNTER);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_CUPBOARD_COUNTER);
               entries.method_45421(BlockInit.OAK_KITCHEN_CABINET);
               entries.method_45421(BlockInit.OAK_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.OAK_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_OAK_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_OAK_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_OAK_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.BIRCH_KITCHEN_CABINET);
               entries.method_45421(BlockInit.BIRCH_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.BIRCH_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.SPRUCE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.SPRUCE_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.SPRUCE_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.JUNGLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.JUNGLE_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.JUNGLE_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.ACACIA_KITCHEN_CABINET);
               entries.method_45421(BlockInit.ACACIA_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.ACACIA_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.DARK_OAK_KITCHEN_CABINET);
               entries.method_45421(BlockInit.DARK_OAK_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.DARK_OAK_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.WARPED_KITCHEN_CABINET);
               entries.method_45421(BlockInit.WARPED_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.WARPED_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_WARPED_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_WARPED_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_WARPED_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.CRIMSON_KITCHEN_CABINET);
               entries.method_45421(BlockInit.CRIMSON_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.CRIMSON_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.MANGROVE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.MANGROVE_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.MANGROVE_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.CHERRY_KITCHEN_CABINET);
               entries.method_45421(BlockInit.CHERRY_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.CHERRY_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_DOUBLE_KITCHEN_CABINET);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_GLASS_KITCHEN_CABINET);
               entries.method_45421(BlockInit.OAK_KITCHEN_SINK);
               entries.method_45421(BlockInit.STRIPPED_OAK_KITCHEN_SINK);
               entries.method_45421(BlockInit.BIRCH_KITCHEN_SINK);
               entries.method_45421(BlockInit.STRIPPED_BIRCH_KITCHEN_SINK);
               entries.method_45421(BlockInit.SPRUCE_KITCHEN_SINK);
               entries.method_45421(BlockInit.STRIPPED_SPRUCE_KITCHEN_SINK);
               entries.method_45421(BlockInit.JUNGLE_KITCHEN_SINK);
               entries.method_45421(BlockInit.STRIPPED_JUNGLE_KITCHEN_SINK);
               entries.method_45421(BlockInit.ACACIA_KITCHEN_SINK);
               entries.method_45421(BlockInit.STRIPPED_ACACIA_KITCHEN_SINK);
               entries.method_45421(BlockInit.DARK_OAK_KITCHEN_SINK);
               entries.method_45421(BlockInit.STRIPPED_DARK_OAK_KITCHEN_SINK);
               entries.method_45421(BlockInit.CRIMSON_KITCHEN_SINK);
               entries.method_45421(BlockInit.STRIPPED_CRIMSON_KITCHEN_SINK);
               entries.method_45421(BlockInit.WARPED_KITCHEN_SINK);
               entries.method_45421(BlockInit.STRIPPED_WARPED_KITCHEN_SINK);
               entries.method_45421(BlockInit.MANGROVE_KITCHEN_SINK);
               entries.method_45421(BlockInit.STRIPPED_MANGROVE_KITCHEN_SINK);
               entries.method_45421(BlockInit.CHERRY_KITCHEN_SINK);
               entries.method_45421(BlockInit.STRIPPED_CHERRY_KITCHEN_SINK);
               entries.method_45421(BlockInit.WHITE_COUCH);
               entries.method_45421(BlockInit.WHITE_CHAISE);
               entries.method_45421(BlockInit.LIGHT_GRAY_COUCH);
               entries.method_45421(BlockInit.LIGHT_GRAY_CHAISE);
               entries.method_45421(BlockInit.GRAY_COUCH);
               entries.method_45421(BlockInit.GRAY_CHAISE);
               entries.method_45421(BlockInit.BLACK_COUCH);
               entries.method_45421(BlockInit.BLACK_CHAISE);
               entries.method_45421(BlockInit.BROWN_COUCH);
               entries.method_45421(BlockInit.BROWN_CHAISE);
               entries.method_45421(BlockInit.RED_COUCH);
               entries.method_45421(BlockInit.RED_CHAISE);
               entries.method_45421(BlockInit.ORANGE_COUCH);
               entries.method_45421(BlockInit.ORANGE_CHAISE);
               entries.method_45421(BlockInit.YELLOW_COUCH);
               entries.method_45421(BlockInit.YELLOW_CHAISE);
               entries.method_45421(BlockInit.LIME_COUCH);
               entries.method_45421(BlockInit.LIME_CHAISE);
               entries.method_45421(BlockInit.GREEN_COUCH);
               entries.method_45421(BlockInit.GREEN_CHAISE);
               entries.method_45421(BlockInit.CYAN_COUCH);
               entries.method_45421(BlockInit.CYAN_CHAISE);
               entries.method_45421(BlockInit.LIGHT_BLUE_COUCH);
               entries.method_45421(BlockInit.LIGHT_BLUE_CHAISE);
               entries.method_45421(BlockInit.BLUE_COUCH);
               entries.method_45421(BlockInit.BLUE_CHAISE);
               entries.method_45421(BlockInit.PURPLE_COUCH);
               entries.method_45421(BlockInit.PURPLE_CHAISE);
               entries.method_45421(BlockInit.MAGENTA_COUCH);
               entries.method_45421(BlockInit.MAGENTA_CHAISE);
               entries.method_45421(BlockInit.PINK_COUCH);
               entries.method_45421(BlockInit.PINK_CHAISE);
            })
            .method_47324()
      );
   }

   public static class_265 rotateFurniture(class_265 shape, int quarterTurns) {
      class_265[] buffer = new class_265[]{shape, class_259.method_1073()};
      quarterTurns %= 4;

      for (int i = 0; i < quarterTurns; i++) {
         buffer[0]
            .method_1089(
               (minX, minY, minZ, maxX, maxY, maxZ) -> {
                  double newMinX = 1.0 - maxZ;
                  double newMaxX = 1.0 - minZ;
                  buffer[1] = class_259.method_1084(
                     buffer[1], class_2248.method_9541(newMinX * 16.0, minY * 16.0, minX * 16.0, newMaxX * 16.0, maxY * 16.0, maxX * 16.0)
                  );
               }
            );
         buffer[0] = buffer[1];
         buffer[1] = class_259.method_1073();
      }

      return buffer[0];
   }
}
